name: ProximityChat
version: '${project.version}'
main: me.logan.proximitychat.ProximityChat
api-version: 1.20
authors: [ Logan ]
description: Proximity chat for minecraft
commands:
  setproximityrange:
    aliases:
      - spr
    permission: proximitychat.setproximityrange
  toggleshowdistance:
    aliases:
      - togglesd
      - tsd
    permission: proximitychat.toggledistance
  setmegaphonerange:
    aliases:
      - setmgpr
      - smpr
    permission: proximitychat.setmegaphonerange
  toggleglobalchat:
    aliases:
      - tgc
    permission: proximitychat.toggleglobalchat
  gc:
    aliases:
      - global
      - globalchat
  gmp:
    aliases:
      - gmp
      - givemp
      - givemegaphone
    permission: proximitychat.megaphone

